### ISSUE TITLE
Pyright hangs when defining cyclic type alias with `Callable` type

### ISSUE THREAD

**Issue by luwqz1** [microsoft/pyright#10287]
**Describe the bug**
Pyright enters an infinite loop when there is a cyclic alias definition with `Callable` type.

**Code or Screenshots**
A minimal repro code sample:
```python
from collections.abc import Callable

type Function[**P, R] = Callable[P, R]
type Cycle[**P, R] = Cycle[P, Function[**P, R]]
```

**Comment by erictraut** [comment]
This is likely the same underlying issue as https://github.com/microsoft/pyright/issues/10187, but I won't know for sure until I investigate further.

**Comment by luwqz1** [comment]
It is possible that this problem is also related to a false positive in the following case:

```python
from collections.abc import Callable

type Cycle[**P, R] = Cycle[P, Callable[P, R]]

x: Cycle[[str], int] = int  # false positive error TypeVar "Cycle" is not subscriptable
```

**Comment by erictraut** [comment]
This is addressed in 1.1.400.

**Comment by qexat** [comment]
1.1.400 does not seem to address this issue: Pyright is still hanging for me.
[playground link](<https://pyright-play.net/?code=GYJw9gtgBAxmA28CmMAuBLMA7AzgOgEMAjGKdCABzBFSgGEDFjkAoF1ATwqSgDEBXLGkxYA2gCpxABQA0UAEoBdKAF56jeMySjZCxey486HGMgnS5S1fRNndAoRmzndSxUA>)

**Comment by erictraut** [comment]
I'm not able to repro the problem in 1.1.400 — either in VS Code or in the pyright playground. It no longer hangs, and a "cyclical definition" error is reported.

Here's what I see when I click on your pyright playground link:

![Image](https://github.com/user-attachments/assets/1c336633-b686-48dc-9b03-81401a0da1e4)

@qexat, are you seeing something different?

**Comment by qexat** [comment]
@erictraut I'll try on my laptop later, but when I tried on my phone on the playground, the errors did not show up and the message "Waiting for server response" (paraphrasing probably) was spinning indefinitely

**Comment by qexat** [comment]
I was finally able to try it out on my laptop, and now I see what's in the screenshot you shared @erictraut, I don't know what happened on mobile
