### ISSUE TITLE
regression: "unecessary #type ignore" reported in stdlib

### ISSUE THREAD

**Issue by bukzor** [microsoft/pyright#10487]
I've pinpointed this regression to 1.401.

```
$ pyright --verbose lib/sudo-gcp/sudo_gcp/__main__.py
Loading pyproject.toml file at ./pyproject.toml
Execution environment: python
  Extra paths:
    ./venv/lib/python3.13/site-packages
  Python version: 3.13
  Python platform: Linux
Found 1 source file
pyright 1.1.401
  ./node_modules/.pnpm/pyright@1.1.401/node_modules/pyright/dist/typeshed-fallback/stdlib/_typeshed/_type_checker_internals.pyi
  ./node_modules/.pnpm/pyright@1.1.401/node_modules/pyright/dist/typeshed-fallback/stdlib/_typeshed/_type_checker_internals.pyi:52:91 - error: Unnecessary "# type: ignore" comment (reportUnnecessaryTypeIgnoreComment)
1 error, 0 warnings, 0 informations
```

By contrast, in 1.1.400

```
[2025-05-21 Wed PM 02:09-0500] buck@macbookpro.lan $ pyright --verbose lib/sudo-gcp/sudo_gcp/__main__.py
Loading pyproject.toml file at ./pyproject.toml
Execution environment: python
  Extra paths:
    ./venv/lib/python3.13/site-packages
  Python version: 3.13
  Python platform: Linux
Found 1 source file
pyright 1.1.400
0 errors, 0 warnings, 0 informations
```

**Comment by bukzor** [comment]
Minimal reproduction:

```
cat > main.py <<EOF
def main():
    pass
EOF

cat >pyproject.toml <<EOF
[tool.pyright]
reportUnnecessaryTypeIgnoreComment = "error"
EOF


virtualenv .venv
./.venv/bin/pip install pyright
./.venv/bin/pyright .
```

**Comment by srittau** [comment]
In fact, we can't update pyright in typeshed due to this bug. The `# type: ignore[misc]` statement in this location is necessary for mypy, and pyright should not warn about it when running our test cases. See python/typeshed#14121. 

Also related #10484

**Comment by pjonsson** [comment]
This issue got 20 thumbs up so I'm guessing a reasonable amount of people are affected by it. I had a memory that Pyright releases were automated, but I seem to have misremembered, what is the planned date for the next release of Pyright?

**Comment by erictraut** [comment]
I plan to release a new version tomorrow (Tuesday), and it will include this fix.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.402.

**Comment by sminnee** [comment]
Not sure how the project relates, but the error is still occurring if you have this env var set:

`PYRIGHT_PYTHON_PYLANCE_VERSION=latest-release`

So do we need a new release of pylance as well?

**Comment by erictraut** [comment]
@sminnee, which version does `pyright --version` show? The `PYRIGHT_PYTHON_PYLANCE_VERSION=latest-release` controls which version of pyright is installed by the [pyright-python](https://github.com/RobertCraigie/pyright-python) wrapper.

**Comment by debonte** [comment]
Pyright 1.1.402 will be in the next prerelease version of Pylance, which likely won't ship until next Wednesday. At that point you'll be able to use `PYRIGHT_PYTHON_PYLANCE_VERSION=latest-prerelease` to get pyright 1.1.402. We won't ship another release (stable) build of Pylance until early July.
