### ISSUE TITLE
Missing kwargs in signature help when using Unpack (PEP 692) with extra items (PEP 728)

### ISSUE THREAD

**Issue by Viicos** [microsoft/pyright#10996]
Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFACqICmAJgCJIDGMZAqiggIaMDWAUAMYAbTgGdRFOgApKCWg2ZkqADxghOAfSQwqEUQF4icAJQAuPlEtROpzChgC%2BNKsCjAArikZSAVD54A7pwgaKK27Fy8ANrkdAC6ZlBc4o58Hl5SxnxAA)

```python
from typing import Any, TypedDict, Unpack


class TD(TypedDict, extra_items=Any):
    a: int


def func(**kwargs: Unpack[TD]): pass



func()

```

<img width="460" height="276" alt="Image" src="https://github.com/user-attachments/assets/0eb2117f-20f7-435b-924c-d615915b896e" />

**VS Code extension or command-line**
pyright

**Comment by erictraut** [comment]
The signature help logic is owned and maintained by the pylance team.

@rchiodo, could you please transfer this to pylance-release? Thanks!

**Comment by rchiodo** [comment]
Do you still want to transfer? @Viicos has submitted a PR in Pyright.

**Comment by erictraut** [comment]
Just noticed that. Leave it for now. Thanks.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.407

**Comment by Viicos** [comment]
Hum, seems like I can still reproduce the issue.. ([playground](https://pyright-play.net/?pythonVersion=3.14&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjADRQCqKCAhlQNb0ByYMASsQCOAVyQgyAKClUANiwDO8qAFkwANyTEAFEQRlKNesQAeMECwD6SGMQjyAvKhgBKAFwSonqO2JwAjK5Q8mYeXj5wAEyBPPxCouKkANpOALrScopQAILuXlCkxMCwJKSk1DBa8sQywPQsgU70AEYNKHRQAFQd7ADuLCBo8oFMrByJqhrEKc5QALQAfFA8KMSBAHQbUhLGUPbZWs5SxmvweqXlB0A)). Perhaps my fix wasn't targeting the right logic?

**Comment by erictraut** [comment]
Seems to be working.

<img width="437" height="99" alt="Image" src="https://github.com/user-attachments/assets/a452b57c-82ea-4ac6-9bc6-fa4cf8574375" />

**Comment by Viicos** [comment]
Sorry can confirm, maybe the playground wasn't updated to the latest version even though it showed 1.1407 (maybe some cache issue).
