### ISSUE TITLE
Variable with annotation "Type[*]" can't be inherit

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#186]
**Describe the bug**
Variable with annotation "Type[*]" can't be inherit. Please see the image below:

![image](https://user-images.githubusercontent.com/3479453/62754022-9ba00500-baa0-11e9-839b-ff2eb3b74a92.png)
_class_a is having correct type hint, but it can't be inherited_

![image](https://user-images.githubusercontent.com/3479453/62754079-eb7ecc00-baa0-11e9-9b20-ef7fe3bd71b9.png)
_If the annotation of class_a is removed, the type hint remains the same, but the inheriting issue has gone_

**To Reproduce**
Write the code in screenshot to reproduce.

**Expected behavior**
A variable of Type[*] should be considered inheritable, with or without explicit type annotation.

**Screenshots or Code**
```
class A: ...

class_a: Type[A] = A

class B(A):...

class B(class_a):...
```

**VS Code extension or command-line**
Using VSCode extension version 1.0.53.

**Additional context**
nope.

**Comment by erictraut** [comment]
Thanks for the suggestion. This will be fixed in the next version of pyright.

**Comment by erictraut** [comment]
This is now fixed in 1.0.54, which I just published.

**Comment by giyyapan** [comment]
Fix confirmed!

**Comment by giyyapan** [comment]
@erictraut I've found there still a problem about this.

My goal is to use the Type[*] syntax to deal with the typing of some untyped external library, and I can't write the type stubs for the whole external library just because I need only one variable to be typed.

Here is what I want to achieve:

![image](https://user-images.githubusercontent.com/3479453/62784531-43ddba00-baf1-11e9-99c1-657ae5a374c3.png)
_this case is OK, _

Note: The external lib class will have typing "Unknown" in real world so it can be assigned to any variable.

Howevery, **if I change the constructor param to `**kw_args`, there's something wrong**:

![image](https://user-images.githubusercontent.com/3479453/62784717-b353a980-baf1-11e9-95ab-40e596deb454.png)
_if class inherits via Type[*] variable, **kw_args in it's signature can't be handled correctly_

This issue gives me about 200 errors in my project! Please give it a look.

And I'm not sure if there's better solution for what I wan't to achieve.

___

Code I used:
```python
from typing import Type, Any, cast

some_external_lib_class = None

class A:
    """ This is the class used to typing an external lib's class """
    def __init__(self, **kw_args):...

alias_A: Type[A] = cast(Any, some_external_lib_class)

class B(alias_A):
    """ this class inherits class A via alias class variable"""
    pass

B(a=1) # <- this gives an error that constructor signature mismatch

class C(A):
    """ this class inherits class A directly """
    pass

C(a=1) # <- this works fine
```

**Comment by giyyapan** [comment]
Created a saperate issue about the problem in my latest comment.
