### ISSUE TITLE
IntelliSense should be case insensitive

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#216]
**Describe the bug**
Current pyright won't suggest keywords and variables that have different case.

![image](https://user-images.githubusercontent.com/3479453/63500080-c2782580-c4fb-11e9-9b19-134fc09c1ca2.png)
_Won't suggest `False` when user type `fal`_

But in all other tools I know (like vscode-python or TypeScript vscode exntesion), it's case insensitive.

![image](https://user-images.githubusercontent.com/3479453/63500339-4b8f5c80-c4fc-11e9-8a95-d984f933b29e.png)
_Suggestions in typescript extension_

![image](https://user-images.githubusercontent.com/3479453/63500431-6a8dee80-c4fc-11e9-8db5-361d89237cfd.png)
_Suggestions in vscode-python_

**Additional Context**
Even the suggestions should contain those have different case, but the "exact match" ones (both characters and cases are matched) should have more weight.

**Comment by erictraut** [comment]
Good suggestion. I've added support for case insensitivity. I've also added support for matches that are within a small edit distance from the target, allowing for missing, added or transposed characters. These are prioritized lower than exact matches. 

This will be included in the next published version.

**Comment by erictraut** [comment]
This is implemented in 1.0.57, which I just published. Please give it a try and let me know what you think.

**Comment by giyyapan** [comment]
Tried this, there's what I think  (including some other issue of completions):

**Inputting `fal` or `tru` still not triggering suggestions `True` or `False`**

![image](https://user-images.githubusercontent.com/3479453/63664138-ea1b0680-c7f7-11e9-9da0-794815812c8b.png)
![image](https://user-images.githubusercontent.com/3479453/63664147-f2734180-c7f7-11e9-81e1-b30cce824b6b.png)
_First trigger `IntelliSense` using shortcut, than input `fal` does triggers suggestion `False` though_

___
**keyword `import` can't be auto-completed using the `from X import Y` syntax**

![image](https://user-images.githubusercontent.com/3479453/63664262-6c0b2f80-c7f8-11e9-83d0-96f733c157a0.png)

___
**Shorter words might should have more weight than longer**

Shorter words are often keyword, local variables, and functions parameters, which has more possibility to be used in certain contexts, thus they should have more weights.

I noticed pyright **does** consider the length of candidate somehow (but more like the alphabet order), like this:
![image](https://user-images.githubusercontent.com/3479453/63663721-19307880-c7f6-11e9-96a2-0248a24b27c6.png)

It's fine for me.

But this case is weird:
![image](https://user-images.githubusercontent.com/3479453/63663159-e2596300-c7f3-11e9-95b7-e657e92f256f.png)

Wonder why `frozenset` is above `from`

_Though I only mentioned "length", I think the best order is `keyword > local vars > function parameter > global vars > imported members > built-in vars` if they have similar text match. But it kind of hard to balance the weight between candidate roles and text match, so the current solution is good enough_

**Comment by erictraut** [comment]
@giyyapan, would you be willing to remove your modified copy of pyright from the VS Code Marketplace now that I've added a setting to disable language service features? I don't want people to be confused by the presence of two extensions called "pyright". Thanks!

**Comment by erictraut** [comment]
This is now implemented in 1.0.58, which I just published. Completion items now all use "fuzzy" matching rules. Previously I used fuzzy matching for only symbol names. I've now extended it to keywords and import names.

**Comment by giyyapan** [comment]
> @giyyapan, would you be willing to remove your modified copy of pyright from the VS Code Marketplace now that I've added a setting to disable language service features? I don't want people to be confused by the presence of two extensions called "pyright". Thanks!

Already unpublished my copy of pyright, thanks for let me know!

![image](https://user-images.githubusercontent.com/3479453/64473479-03c63180-d19a-11e9-9b0c-4bacffe0bf0c.png)
_only now "pyright" now, cheers!_
