### ISSUE TITLE
Unable to pass `ParamSpec` from wrapper function to implementation

### ISSUE THREAD

**Issue by bryanforbes** [microsoft/pyright#2348]
**Describe the bug**
Given the following code:
```python
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Generic, overload
from typing_extensions import ParamSpec, TypeAlias

P = ParamSpec('P')
CommandHandler: TypeAlias = Callable[P, dict[str, Any]]


class Command(Generic[P]):
    __slots__ = ('handler',)

    def __init__(self, handler: CommandHandler[P]) -> None:
        self.handler: CommandHandler[P] = handler


class Application:
    __slots__ = ('commands',)

    def __init__(self) -> None:
        self.commands: dict[str, Command[Any]] = {}

    def add_command(self, handler: CommandHandler[P]) -> Command[P]:
        # ERROR: Command[()] cannot be passed to Command[P@Command]
        #   P@Command is invariant
        return Command(handler)

    @overload
    def command(self) -> Callable[[CommandHandler[P]], Command[P]]:
        ...

    @overload
    def command(self, handler: CommandHandler[P]) -> Command[P]:
        ...

    def command(
        self, handler: CommandHandler[P] | None = None
    ) -> Command[P] | Callable[[CommandHandler[P]], Command[P]]:
        def decorator(handler: CommandHandler[P]) -> Command[P]:
            # ERROR: Command[P@add_comment] cannot be assigned to Command[P@Command]
            #   P@Command is invariant
            return self.add_command(handler)

        if handler is None:
            return decorator
        else:
            return decorator(handler)


app = Application()


@app.command
def handler_one(arg1: int, arg2: str) -> dict[str, Any]:
    return {}


@app.command()
def handler_two(arg1: str, arg2: int) -> dict[str, Any]:
    return {}


handler_one  # Command[P@command]
handler_two  # Command[P@command]
```

Passing `P` from `Application.add_command` to `Command` and from `Application.command` to `Application.add_command` reports an error

**Expected behavior**
`P` should be inferred correctly in both places (instead of `()` in some cases), and `P` being invariant should not generate an error in these cases.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line

Which version?
1.1.171

**Additional context**
If `P` is changed to `Any` in the signature of `Application.add_command`, the above errors are no longer generated, but the following error is generated:

```
Could not specialize type "CommandHandler[P@CommandHandler]"
Type "Any" is incompatible with ParamSpec "P"
```

**Comment by erictraut** [comment]
Thanks for the bug report. Upon initial investigation, this has to do with a generic type alias that is parameterized with a ParamSpec. I didn't contemplate that use case when I wrote the ParamSpec code initially, and we don't have any coverage of this in our unit tests. I agree that it's a valid use case though, so I'll work on addressing this.

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.172, which I just published. It will also be in the next release of pylance.

**Comment by bryanforbes** [comment]
Thank you for your fast response!

**Comment by bryanforbes** [comment]
Pyright 1.1.172 has fixed the first error in the code example I gave, but it doesn't fix the second error. Could you please re-open this?

**Comment by erictraut** [comment]
Ah, you're right.

**Comment by erictraut** [comment]
This was a slightly different bug than the first. It's now fixed as well.

You're using ParamSpecs in clever ways that I haven't seen before. Thanks for reporting these issues.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.173, which I just published. It will also be included in the next release of pylance.
