### ISSUE TITLE
Position-only parameter mismatch with TypeVarTuple and Callable type

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pyright#3499]
**To Reproduce**

```py
from typing import Callable, Generic
from typing_extensions import TypeVarTuple, Unpack

Ts = TypeVarTuple("Ts")

class Job(Generic[Unpack[Ts]]):
    def __init__(self, target: Callable[[Unpack[Ts]], int]) -> None:
        self.target = target


def f(a: int, b: str) -> int: ...

x = Job(f)
reveal_type(x)  # Job[int, str]


def g(action: Callable[[int, str], int]):
    y = Job(action)  # -> error
    reveal_type(y)


def h(action: Callable[[int], int]):
    z = Job(action)
    reveal_type(z)  # Job[int]
```

```
  test.py:14:13 - information: Type of "x" is "Job[int, str]"

  test.py:18:13 - error: Argument of type "(int, str) -> int" cannot be assigned to parameter "target" of type "(*Ts@Job) -> int" in function "__init__"
    Type "(int, str) -> int" cannot be assigned to type "(*Ts@Job) -> int"
      Position-only parameter mismatch; expected 2 but received 1 (reportGeneralTypeIssues)

  test.py:18:5 - error: Type of "y" is partially unknown
    Type of "y" is "Job[Unknown]" (reportUnknownVariableType)
  test.py:19:17 - information: Type of "y" is "Job[Unknown]"
  test.py:24:17 - information: Type of "z" is "Job[int]"
```

**Expected behavior**
`reveal_type(y)` should also be `Job[int, str]` similar to `reveal_type(x)`.

**VS Code extension or command-line**
v1.1.248

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.249, which I just published. It will also be included in the next release of pylance.

**Comment by cdce8p** [comment]
Just tested `1.1.249`. It seems the updated didn't fix the issue, unfortunately. Instead, it added a new issue for `z` which could be inferred previously.
```
  test.py:14:13 - information: Type of "x" is "Job[int, str]"
  test.py:18:13 - error: Argument of type "(int, str) -> int" cannot be assigned to parameter "target" of type "(**P@Job) -> None" in function "__init__"
    Type "(int, str) -> int" cannot be assigned to type "(**P@Job) -> None"
      Function return type "int" is incompatible with type "None"
        Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  test.py:18:5 - error: Type of "y" is partially unknown
    Type of "y" is "Job[(*args: Unknown, **kwargs: Unknown)]" (reportUnknownVariableType)
  test.py:19:17 - information: Type of "y" is "Job[(*args: Unknown, **kwargs: Unknown)]"
  test.py:23:13 - error: Argument of type "(int) -> int" cannot be assigned to parameter "target" of type "(**P@Job) -> None" in function "__init__"
    Type "(int) -> int" cannot be assigned to type "(**P@Job) -> None"
      Function return type "int" is incompatible with type "None"
        Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  test.py:23:5 - error: Type of "z" is partially unknown
    Type of "z" is "Job[(*args: Unknown, **kwargs: Unknown)]" (reportUnknownVariableType)
  test.py:24:17 - information: Type of "z" is "Job[(*args: Unknown, **kwargs: Unknown)]"
```

**Comment by erictraut** [comment]
I'm not able to repro any errors with the code sample above and with pyright 1.1.249.

Here is the output I receive:
```python
  test.py:14:13 - information: Type of "x" is "Job[int, str]"
  test.py:19:17 - information: Type of "y" is "Job[int, str]"
  test.py:24:17 - information: Type of "z" is "Job[int]"
```

Is it possible that you have an outdated `typing_extensions-stub` installed in your environment? Please try to repro with a clean environment.

**Comment by cdce8p** [comment]
You're right, sorry for the confusion. I had a snipped for another issue in the same file which caused the wrong output.
