### ISSUE TITLE
Function parameter autocompletion not working for decorators

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#461]
**Describe the bug**
When a function is called with `@` prefix, function parameters can't be autocompleted inside its parentheses.

Please see this example:
![image](https://user-images.githubusercontent.com/3479453/71616119-98dcb280-2bef-11ea-97b7-5218c82dadf7.png)
![image](https://user-images.githubusercontent.com/3479453/71616125-a4c87480-2bef-11ea-87af-19ec369655eb.png)

**Expected behavior**
Function parameters can be suggested when the function is used as a decorator.

**Code**
```
from functools import wraps


def some_decorator_creator(check: bool):
    def decorator(func):

        @wraps(func)
        def wrapper(*args, **kwargs):
            if check:
                # do some stuff
                pass
            return func(*args, **kwargs)

        return wrapper
    return decorator

# parameter "check" is in the completion suggestion
some_decorator_creator()

# parameter "check" is NOT in the completion suggestion
@some_decorator_creator()
def fn():
    pass
```

**VS Code extension or command-line**
VSCode extension 1.1.16

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright.

**Comment by erictraut** [comment]
This fix is included in Pyright v1.1.17, which I just published.

**Comment by giyyapan** [comment]
@erictraut 
Thanks for fixing the bug, the decorator function can have parameter name suggestion now.
But I still have some questions about this. Please see these examples.
### Problem 1
```python
from functools import wraps

def user_auth(privilege:str = None):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            return func(*args, **kwargs)
        return wrapper
    return decorator

# When called as a normal function
# put the cursor between parentheses and exec command "Trigger Suggest (editor.action.triggerSuggest)"
# the parameter name privilege will appear
user_auth()

# When called as decorator function
# put the cursor between parentheses and exec command "Trigger Suggest (editor.action.triggerSuggest)"
# there will be no parameter name, which is different from the normal behavior
# But if there is at least on correct character, the parameter name suggestion will appear
@user_auth()
def fn():
    pass
```
[Correct] Called as a normal function
![image](https://user-images.githubusercontent.com/3479453/72038529-b0e1bf80-32dc-11ea-8b06-7fdf2f7338b5.png)

[Wrong] Called as decorator function
![image](https://user-images.githubusercontent.com/3479453/72038538-b6d7a080-32dc-11ea-88b5-922774616414.png)

[Correct] Called as decorator function and input one correct character between parentheses
![image](https://user-images.githubusercontent.com/3479453/72038550-c5be5300-32dc-11ea-9868-9e91e63da3ee.png)

### Problem 2
```python
from functools import wraps

def user_auth(privilege:str = None):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            return func(*args, **kwargs)
        return wrapper
    return decorator

class SomeClass:
    some_property: str

instance = SomeClass()

# When called as a normal function
# If we are using "instance.some_property" as function parameter
# the autocomplete of property name for variable "instance" works correctly
user_auth(instance.)

# When called as a decorator function
# If we are using "instance.some_property" as function parameter
# the autocomplete of property name for variable "instance" not working
# But, like the previous example, if at least one correct character is inputted,
# the suggestion will become correct
@user_auth(instance.)
def fn():
    pass
```
[Correct] Called as a normal function
![image](https://user-images.githubusercontent.com/3479453/72038889-feaaf780-32dd-11ea-877f-afd2a25a64a8.png)

[Wrong] Called as decorator function
![image](https://user-images.githubusercontent.com/3479453/72038956-37e36780-32de-11ea-9dee-31e8b4b6010f.png)

[Correct] Called as decorator function and input one correct character after dot
![image](https://user-images.githubusercontent.com/3479453/72038972-492c7400-32de-11ea-9a03-f0eeb2c0e990.png)

Decorators with parameters are widely used in our project, so these small issues can be quite annoying. Please let me know if you need more information.

Thank you very much!

**Comment by erictraut** [comment]
Thanks for the great bug reports. I was easily able to repro the problems and fix them. It turned out to be two separate bugs — one in the completion provider and a second in the parser. They'll both be fixed in the next release.

**Comment by erictraut** [comment]
This is now fixed in 1.1.19, which I just published.

**Comment by giyyapan** [comment]
Creat!
I just upgraded Pyright and confirmed both of the two bugs are gone. Thanks for your great work!

However, I noticed a new issue that might be related, if that's an unrelated bug then I'll open a new issue.

Please see this example.
```python
from functools import wraps

class SomeClass:
    def decorator_method(self):
        def decorator(func):
            @wraps(func)
            def wrapper(*args, **kwargs):
                return func(*args, **kwargs)
            return wrapper
        return decorator

some_class = SomeClass()

# In a normal use case, if we input "some_class.", it's method can be suggested
some_class.

# But if prefixed with "@", the class methods are no longer suggested
# Unlike the previously reported bug, there will be no correct suggestion
# with or without correct leading characters
@some_class.
```

[Correct] Referenced directly
![image](https://user-images.githubusercontent.com/3479453/72238654-54064200-3619-11ea-95b6-b24d29db534e.png)

[Wrong] With "@" prefix
![image](https://user-images.githubusercontent.com/3479453/72238665-5ec0d700-3619-11ea-8b8b-3a5277b761f6.png)

[Wrong] With "@" prefix and leading character inputted
![image](https://user-images.githubusercontent.com/3479453/72238674-6bddc600-3619-11ea-922f-aca75eca449f.png)

This issue also happens on imported packages.
```python
# in file app/test2.py
def method_a():
    pass

def method_b():
    pass
```
```python
# in file app/test.py
from app import test2

# Correct function name suggestions
test2.

# Wrong function name suggestions
@test2.
```

[Correct] Referenced directly
![image](https://user-images.githubusercontent.com/3479453/72238927-443b2d80-361a-11ea-8075-22f5431639a6.png)

[Wrong] With "@" prefix
![image](https://user-images.githubusercontent.com/3479453/72238958-587f2a80-361a-11ea-9c1c-af69191b6229.png)

[Wrong] With "@" prefix and leading character inputted
![image](https://user-images.githubusercontent.com/3479453/72238971-659c1980-361a-11ea-8cd9-8fcfbf62a30a.png)

Thank you very much.

**Comment by erictraut** [comment]
This is a different issue, but it is indeed another bug. Thanks for finding and reporting these!

In case you're curious, this bug is related to the fact that the parser was looking for a valid function or class declaration after the decorator. Because it didn't find it, it produced no parse node. But that meant that the type completion logic had no parse information to work from. I've changed the parser to generate a dummy parse node if it finds a decorator with no corresponding function or class declaration. This fixes the problem.

**Comment by giyyapan** [comment]
You are correct, I just tried it myself and it's true that if the decorator is followed by a valid function, it will have better suggestions.

However, the suggestion of methods still not provided unless some leading character was provided.

```python
class SomeClass:
    def method_a():
        pass

@SomeClass.
def fn():
    pass
```
name `method_a` was not suggested.
![image](https://user-images.githubusercontent.com/3479453/72349380-61095b00-3717-11ea-8e0a-c8630e81469f.png)

name `method_a` was suggested if there are leading characters.
![image](https://user-images.githubusercontent.com/3479453/72349432-7e3e2980-3717-11ea-81b0-0090fe7f780d.png)

Just in case you miss this little difference : )

**Comment by erictraut** [comment]
This is now fixed in 1.1.21. Thanks again for reporting these problems. Keep the bug reports and feature requests coming!
