### ISSUE TITLE
Slow performance with lightgbm package

### ISSUE THREAD

**Issue by bschnurr** [microsoft/pyright#4787]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**

`[BG(1)] Long operation: checking: d:\dev\bschnurr\pyls-benchmarks\ds\src\test2.py (14604ms)`

**To Reproduce**
Steps to reproduce the behavior.

1.  pip install lightgbm in python3.9 .env folder
2.  enable  `useLibraryCodeForTypes`
pyrightconfig
```json
{
    "useLibraryCodeForTypes" : true
}

```
**Expected behavior**

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
import lightgbm as lgb
from scipy.sparse import vstack

lgb_model = lgb.LGBMClassifier(max_depth=-1,
                                   n_estimators=30000,
                                   learning_rate=0.05,
                                   num_leaves=2**12-1,
                                   colsample_bytree=0.28,
                                   objective='binary', 
                                   n_jobs=-1)


X_val = vstack([])
lgb_model.predict_proba(X_val)
```

logs with trace and
```json
    "python.analysis.logTypeEvaluationTime": true,
    "python.analysis.typeEvaluationTimeThreshold": 500,
```
[pyright_lightgbm_logs.txt](https://github.com/microsoft/pyright/files/10991805/pyright_lightgbm_logs.txt)

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**

issue seems to be evaluating lightgbm\basic.py 's  `get_data()` function  when `X_val` is a union of scipy's types.

![image](https://user-images.githubusercontent.com/1946977/225649350-e6a6ef80-df97-4f7c-baa9-b85c7857b6c9.png)

sample pulled from logs
```
										xe ["self.data.iloc[self.used_indic <shortened> " (lightgbm.basic) [2323:33]] (4124ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4124ms)
[BG(1)]                             xe ["self.get_data" (lightgbm.basic) [1805:25]] (4148ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4148ms)
[BG(1)]                           xe ["self.set_group" (lightgbm.basic) [1807:25]] (4148ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4148ms)
[BG(1)]                         xe ["self.get_label" (lightgbm.basic) [1808:24]] (4148ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4148ms)
[BG(1)]                       xe ["self.reference._predictor" (lightgbm.basic) [1810:96]] (4148ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4148ms)
[BG(1)]                     xe ["self.get_data" (lightgbm.basic) [1811:25]] (4148ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4148ms)
[BG(1)]                   xe ["self._set_init_score_by_predic <shortened> " (lightgbm.basic) [1812:25]] (4148ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4148ms)
[BG(1)]                 xe ["train_set.construct" (lightgbm.basic) [2605:13]] (4739ms) [f:2, t:0, p:1, i:3, b:1]
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4739ms)
[BG(1)]               xe ["params.update" (lightgbm.basic) [2607:13]] (4744ms) [f:2, t:0, p:1, i:3, b:1]
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4744ms)
[BG(1)]             xe ["predictor.predict" (lightgbm.basic) [3538:16]] (4804ms) [f:7, t:2, p:6, i:12, b:10]
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (4804ms)
[BG(1)]           xe ["self._Booster.predict" (lightgbm.sklearn) [803:16]] (6866ms) [f:28, t:30, p:103, i:101, b:86]
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (6866ms)
[BG(1)]         xe ["super().predict" (lightgbm.sklearn) [997:18]] (6867ms) [f:28, t:30, p:103, i:101, b:86]
[Info  - 7:20:19 AM] [BG(1)] Long operation: xe (6867ms)
[BG(1)]       Fe ["lgb_model.predict_proba(X_val) <shortened> " (test2) [14:1]] (6940ms) [f:29, t:38, p:128, i:114, b:110]
[Info  - 7:20:19 AM] [BG(1)] Long operation: Fe (6940ms)
[BG(1)]     checking: d:\dev\bschnurr\pyls-benchmarks\ds\src\test2.py (14604ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: checking: d:\dev\bschnurr\pyls-benchmarks\ds\src\test2.py (14604ms)
[BG(1)]   analyzing: d:\dev\bschnurr\pyls-benchmarks\ds\src\test2.py (14815ms)
[Info  - 7:20:19 AM] [BG(1)] Long operation: analyzing: d:\dev\bschnurr\pyls-benchmarks\ds\src\test2.py (14815ms)

```

**Comment by erictraut** [comment]
Pyright already special-cases `__init__` and doesn't attempt to infer its return type.

![image](https://user-images.githubusercontent.com/7040122/225757792-dcd96518-f299-4f7f-b7d2-75a4b8408f7c.png)

**Comment by erictraut** [comment]
I've spent a good deal of time looking into this issue. The primary reason for the slow performance is that the functions in `lightgbm` use very deep call chains, and most of the invoked functions or methods are unannotated. Inferring the return type of these functions would be generally unnecessary except that the code flow engine needs to determine whether each of these calls is a "NoReturn" call — i.e. a call that doesn't return control back to the caller. 

I've prepared a PR that modifies the behavior of the code flow engine such that it assumes all unannotated functions return control back to the caller — i.e. none of them are `NoReturn` calls. By making this assumption, we can skip a bunch of the work. 

With this behavior change, completion suggestions for `lightgbm` are nearly instantaneous (a few 100's of milliseconds) rather than 4K+ milliseconds.

The downside is this change is that type analysis will be less accurate in certain cases. We'll need to decide whether the tradeoff is worth it. It would be good to run this PR through the benchmarks to see what impact it has. It might also be worth releasing a prerelease version of pylance with this change to get early feedback from users.

**Comment by heejaechang** [comment]
@debonte we probably want to do one more hotfix tomorrow?

**Comment by heejaechang** [comment]
@erictraut after the fix, showing completion for predict_proba off lgb_model got faster 

```python
lgb_model.predict_proba(X_val)
```

but hovering over predict_proba is still slow. can that be improved as well?

**Comment by erictraut** [comment]
I'm not able to repro slow behavior with hovering over `predict_proba`. If I make a modification to the file and then immediately hover over `predict_proba`, the hover appears almost instantaneously for me, and there is no "long operation" printed in the logs. Are you seeing a long operation in this case?

**Comment by erictraut** [comment]
This is included in pyright 1.1.300, which I just published. It will also be included in a future release of pylance.

**Comment by heejaechang** [comment]
> I'm not able to repro slow behavior with hovering over predict_proba. If I make a modification to the file and then immediately hover over predict_proba, the hover appears almost instantaneously for me, and there is no "long operation" printed in the logs. Are you seeing a long operation in this case?

sorry for late reply. Yes. I still get the long operation log. 

![image](https://user-images.githubusercontent.com/1333179/226874831-18dcce0a-044a-4795-bcd8-52889f42e393.png)
