### ISSUE TITLE
Import 'yaml' could not be resolved

### ISSUE THREAD

**Issue by manatlan** [Microsoft/pyright#53]
**Describe the bug**
Hi, I'm new to pyright (in vscode) ... it's perhaps a dumb question, but I don't reach to resolve myself ;-)

Why this script works like a charm
![Capture du 2019-04-04 18-14-11](https://user-images.githubusercontent.com/150722/55571386-b682f700-5705-11e9-869e-6ee0b419958d.png)
and why the import statement is red-underlined (Import 'yaml' could not be resolved) ?

**To Reproduce**
pip install pyyaml, run vscode, type the script

**Expected behavior**
the import statement should be ok

**Additional context**
I don't use any venv thing. It's only pure installed python3, under ubuntu latest LTS

**Comment by erictraut** [comment]
If you haven't specified any virtual environment or other configuration options, Pyright should use your PYTHONPATH environment variable to find the import paths. What is your PYTHONPATH env variable set to?

For details on Pyright's import resolution, refer to [this documentation](https://github.com/Microsoft/pyright/blob/master/docs/import-resolution.md).

**Comment by manatlan** [comment]
I don't have any "PYTHONPATH" env vars  (echoing $PYTHONPATH is empty)

**Comment by erictraut** [comment]
Then Pyright has no way of knowing where to look for your installed python files. You'll need to define PYTHONPATH or configure pyright to use a virtual environment.

**Comment by manatlan** [comment]
Thanks

**Comment by manatlan** [comment]
Why pyright doesn't implement a feature like that:
if $PYTHONPATH is empty, it create its own pythonpath with sys.path (or "python -m site" paths), with current python version ?

**Comment by erictraut** [comment]
That's a good suggestion. I just implemented it, and I'll include it in the next version.

**Comment by deepdatalive** [comment]
+1 facing this same issue still in vscode environment is configured, script runs properly but still the import error

**Comment by sudhir415** [comment]
python -m pip install pyyaml

run this command in your terminal it will resolve your issue.

**Comment by ReHoss** [comment]
> python -m pip install pyyaml
> 
> run this command in your terminal it will resolve your issue.

Hi there, I don't think this is the preferred solution, as running this python command will install `pyyaml` on the system rather than some virtual environment.

It is better to install `pyyaml` inside your `conda` or `venv` and link that environment to `pyright`, as suggested by @erictraut

**Comment by SvyatKtsov** [comment]
> python -m pip install pyyaml
> 
> run this command in your terminal it will resolve your issue.

thank you so much, it worked for me!
