### ISSUE TITLE
Metaclass overriding `__call__` will break the annotation of the `__init__` in the newly defined class.

### ISSUE THREAD

**Issue by cainmagi** [microsoft/pyright#5488]
## **Describe the bug**

Previously, if we override the `__call__(...)` method of a metaclass, it will not influence the annotation of any classes defined with this metaclass. However, this behavior has changed since one week ago. Today I have updated my Pylance to `2023.7.10` (with pyright `74d8f3c4`). But this issue still exists.

The main problem is that the signature of the metaclass `__call__(...)` overrides that of the `__init__(...)`, which causes the instantiation of the class totally loses its annotation. I will provide the example in **To reproduce** later.

## **Codes, screenshots, and how to Reproduce**

```python
from typing_extensions import reveal_type

class TestMeta(type):
    def __call__(cls, *args, **kwargs):
        return super().__call__(*args, **kwargs)


class Test(metaclass=TestMeta):
    def __init__(self, val1: str, val2: int) -> None:
        ...


# Here, `val1` is provided with the wrong type. However, no error is 
# thrown because the type check uses the signature of `TestMeta.__call__(...)`
val_test = Test(val1=1, val2=2)
# val_test is annotated as `Any`, but the Python run-time result is Test.
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/28806346-b70b-4172-a6e7-fddef962e7f2)

</details>

Furthermore, I can confirm the metaclass's signature causes this issue. If I make some modifications like this, the results will be very "interesting":

```python
from typing_extensions import reveal_type


class TestMeta(type):
    def __call__(cls, *args, **kwargs) -> int:
        return super().__call__(*args, **kwargs)


class Test(metaclass=TestMeta):
    def __init__(self, val1: str, val2: int) -> None:
        ...


# Now the type of the result is faked as a `int`.
val_test = Test(anything="lmao")
# val_test is annotated as `int`, but the Python run-time result is Test.
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/3035c648-ef55-4601-b71c-8050704abcce)

</details>

I think the above usage is illegal. Even though the signature of the metaclass should be used for type checking, there should be a check for verifying whether the class definition `class Test(metaclass=TestMeta)` is compatible with the metaclass `TestMeta.__call__`. If not, an error should be thrown on this line. Currently, no errors are thrown in the above codes, although the usage is not correct.

## **My understanding**

After some experiments, I find that the type checker will do the following thing when checking `Test(...)`:

1. Check the metaclass first. If the usage of `Test(...)` matches the signature of `TestMeta.__call__(...)`, use the metaclass signature to validate the type.
2. If the metaclass signature does not match the usage, the signature of `Test.__init__(...)` will still not be used, but the returned type of `Test(...)` will be correct.

The following example can prove my understanding:

```python
from typing_extensions import reveal_type


class TestMeta(type):
    def __call__(cls, cannot_match: bool) -> int:
        return super().__call__(cannot_match)


class Test(metaclass=TestMeta):
    def __init__(self, val1: str, val2: int) -> None:
        ...


# Although the usage matches `Test.__init__()`, it still raise the error.
val_test = Test(val1="ss", val2=23)
# val_test is annotated as `Test` because no signature can be found in the metaclass.
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/a57f0fa1-41d0-424c-9b20-026f5dc97449)

</details>

I think this behavior is definitely a bug because, in most cases, the `__call__` of metaclass is defined for accepting arbitrary variables. The signature of the metaclass `__call__` should not be treated as superior to the `__init__`.

## **Extended studies**

I want to find out whether I can overcome this issue by providing more type hints to `TestMeta.__call__`. But all my tries have their limitation. Here I will explain my fixtures as follows.

### Use `Type[T]`

The first thing I came up with is to provide the type of returned value. This method can only fix the returned value of `Test(...)`, but the check of the input variables is still wrong.

```python
from typing import Type, TypeVar
from typing_extensions import reveal_type


T = TypeVar("T")


class TestMeta(type):
    def __call__(cls: Type[T], *args, **kwargs) -> T:
        return super().__call__(*args, **kwargs)


class Test(metaclass=TestMeta):
    def __init__(self, val1: str, val2: int) -> None:
        ...


# Now the returned value can be correctly annotated, but the signature of the input
# variables does still match `__init__``
val_test = Test(val_anything=True)
# val_test is annotated as `Test` because no signature can be found in the metaclass.
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/56e5f148-b709-418f-afaf-421b5219dc69)

</details>

### Use `Callable[P, T]`

Then I thought I could also annotate the input arguments of `TestMeta.__call__`.

```python
from typing import Callable, Generic, TypeVar
from typing_extensions import ParamSpec, reveal_type


P = ParamSpec("P")
T = TypeVar("T")


class TestMeta(type):
    def __call__(cls: Callable[P, T], *args: P.args, **kwargs: P.kwargs) -> T:
        return super().__call__(*args, **kwargs)


class Test(Generic[T], metaclass=TestMeta):
    def __init__(self, val1: T, val2: int) -> None:
        ...


# This implementation works when `Test` is not generic. However, if it is generic,
# using Paramspec will cause the signature loses its generic type.
val_test = Test(val1=1, val2=2)
# val_test is annotated as `Test[T@Test]`, where `T@Test` is not solved as `int`
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/c4aa39a1-cda5-4f06-84fb-c12c97d2e3ed)

</details>

### Use `Protocol[P]`

I have also tried to replace `Callable` with a more complete thing like a general protocol. However, the behavior is still not improved at all.

The first implementation of `Protocol` does not annotate the returned value. This implementation cannot be used because it will cause `Test(...)` to be annotated as the protocol instance. It is interesting that a protocol should not be instantiated. So there may need some extra work to forbid the protocol instances to be the returned value.

```python
from typing import Type, Generic, TypeVar
from typing_extensions import Protocol, ParamSpec, reveal_type


P = ParamSpec("P")
T = TypeVar("T")


class TestProtocol(Protocol[P]):
    # It is not allowed to annotate `self`` as `T` here.
    def __init__(self, *args: P.args, **kwargs: P.kwargs) -> None:
        ...


class TestMeta(type):
    # If we do not annotate the returned value, the returned value will be annotated
    # any `Any` automatically.
    def __call__(
        cls: Type[TestProtocol[P]], *args: P.args, **kwargs: P.kwargs
    ) -> TestProtocol[P]:
        return super().__call__(*args, **kwargs)


class Test(Generic[T], metaclass=TestMeta):
    def __init__(self, val1: T, val2: int) -> None:
        ...


# This implementation works when `Test` is not generic. However, if it is generic,
# using Paramspec will cause the signature loses its generic type.
val_test = Test(val1=1, val2=2)
# val_test is annotated as `TestProtocol[(val1: T@Test, val2: int)]`, however, we
# expect to get `Test[int]`.
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/f290282e-2abf-475e-8c23-74d98b7efbdb)

</details>

### Use `Protocol[P, T]`

This time, I tried to let the protocol provide the instance annotation `T_co`. It performs similarly to `Callable[P, T]` because the generic type `T@Test` is still not solved correctly.

```python
from typing import Type, Generic, TypeVar
from typing_extensions import Protocol, ParamSpec, reveal_type


P = ParamSpec("P")
T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)


class TestProtocol(Protocol[P, T_co]):
    # It is not allowed to annotate `self`` as `T` here.
    def __init__(self, *args: P.args, **kwargs: P.kwargs) -> None:
        ...

    # If we do not annotate `T_co`, the returned value of `Test(...)` will be annotated
    # as `T_co@TestProtocol``
    def __new__(cls: Type[T_co]) -> T_co:
        ...


class TestMeta(type):
    def __call__(cls: Type[TestProtocol[P, T]], *args: P.args, **kwargs: P.kwargs) -> T:
        return super().__call__(*args, **kwargs)


class Test(Generic[T], metaclass=TestMeta):
    def __init__(self, val1: T, val2: int) -> None:
        ...


# This implementation works when `Test` is not generic. However, if it is generic,
# using Paramspec will cause the signature loses its generic type.
val_test = Test(val1=1, val2=2)
# val_test is annotated as `Test[Unknown]`, at least it is not `T@Test` this time.
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/e7775335-b26d-4136-b387-81af433f575b)

</details>

### The only perfect solution is ugly!

Finally, I find that the only solution working perfectly is to make the signature of `TestMeta.__call__` totally the same as `Test.__init__`. However, I am not very satisfied with this situation because a metaclass should be able to be used for defining different classes. This implementation will require defining a customized metaclass for each class particularly.

```python
from typing import Generic, TypeVar
from typing_extensions import reveal_type


T = TypeVar("T")


class TestMeta(type):
    # This ugly solution works perfectly, but we have to define different
    # metaclass for different usages, which will cause a lot of redundant work.
    def __call__(
        cls, val1: T, val2: int
    ) -> "Test[T]":
        return super().__call__(val1, val2)


class Test(Generic[T], metaclass=TestMeta):
    def __init__(self, val1: T, val2: int) -> None:
        """eee"""
        ...


# Now both the input and returned value are correctly solved. Even the docstring of
# `__init__` can be preserved.
val_test = Test(val1=1, val2=2)
# val_test is annotated as `Test[int]` now.
reveal_type(val_test)
```

<details>
  <summary>Click this to see the screenshot :framed_picture:</summary>

![image](https://github.com/microsoft/pyright/assets/32186723/d1513ff3-ded2-407e-9fc7-c3c2bcd1deef)

</details>

### Improve the solution by `overload`

The above solution can be improved by using `overload`. This solution is the version approaching my expectation most. It has the same performance compared to the previous ugly one. The only drawback of this solution is that at least two overloads need to be provided, which requires us to provide a `Never` overload for handling the "others" cases.

```python
from typing import Type, Generic, TypeVar
from typing_extensions import Never, reveal_type, overload


T = TypeVar("T")


class TestMeta(type):
    @overload
    def __call__(cls: Type["Test[T]"], val1: T, val2: int) -> "Test[T]":
        ...

    @overload
    def __call__(cls, *args, **kwargs) -> Never:
        ...

    def __call__(cls, *args, **kwargs):
        return super().__call__(*args, **kwargs)


class Test(Generic[T], metaclass=TestMeta):
    def __init__(self, val1: T, val2: int) -> None:
        ...


val_test = Test(val1=1, val2=2)
# val_test is annotated as Test[int]
reveal_type(val_test)
```

## **Expected behavior**

After the above experiments. I think the algorithm for solving the `Test(...)` signature should follow these steps:

1. Try to match the usage `Test(...)` with `Test.__init__(...)` first. If it matches, return the type hints.
2. If not, try to match the overloads of the metaclass `TestMeta.__call__`. If no overload is provided in the metaclass, even if the usage matches the metaclass signature, it still raises an error.
3. If overloads of the metaclass `__call__` are provided, use the failure messages from the metaclass as the returned error.
4. If not overloads of the metaclass `__call__` is provided, use the failure message from `Test.__init__` as the returned error.

Another possible solution is checking whether the implementation of `TestMeta.__call__` is `(cls, *args, **kwargs)`. If so, simply ignore this signature when performing the type check.

Finally, I expect that the following solution can work:

```python
from typing import Generic, TypeVar
from typing_extensions import reveal_type


T = TypeVar("T")


class TestMeta(type):
    def __call__(cls, *args, **kwargs):
        return super().__call__(*args, **kwargs)


class Test(Generic[T], metaclass=TestMeta):
    def __init__(self, val1: T, val2: int) -> None:
        ...


val_test = Test(val1=1, val2=2)
# val_test is expected to be annoated as Test[int].
reveal_type(val_test)
```

**Comment by erictraut** [comment]
I recently changed pyright's evaluation of constructor calls to better reflect the runtime behavior. This was an intentional change. The old logic was similar to what you describe above, and it didn't properly handle a number of edge cases, including certain custom metaclass `__call__` overrides. I don't have any plans to go back to the old logic flow.

If a metaclass provides a custom `__call__` method, then a static type checker generally cannot make assumptions about what it does within that `__call__`. It might call through to the standard `new.__call__` or it might implement its own custom logic. The only thing a static type checker can go on is the type information provided in the `__call__` signature.

It looks like your metaclass is calling through to the standard `new.__call__` to perform most of its work. Could you provide more information about why you are overriding `__call__` in this manner? Is this just for an internal test class, or is this used in production code?

Currently the logic always skips `__new__` and `__init__` validation if there is a custom metaclass `__call__`. Perhaps the right answer here is to modify this to validate `__new__` and `__init__` if the metaclass `__call__` returns an instance of the `cls` type, which is the normal expected behavior for `__call__`. This would still make assumptions about the internal implementation about the `__call__` method that might be incorrect. For example, what if the `__call__` method does not call `__init__` on the class?

Another option is to leave the logic the way it is currently, and if you override `__call__` in your metaclass but want a static type checker to use the normal `new.__call__` logic, you could conditionalize the override with an `if not TYPE_CHECKING:` conditional.

**Comment by cainmagi** [comment]
> I recently changed pyright's evaluation of constructor calls to better reflect the runtime behavior. This was an intentional change. The old logic was similar to what you describe above, and it didn't properly handle a number of edge cases, including certain custom metaclass `__call__` overrides. I don't have any plans to go back to the old logic flow.
> 
> If a metaclass provides a custom `__call__` method, then a static type checker generally cannot make assumptions about what it does within that `__call__`. It might call through to the standard `new.__call__` or it might implement its own custom logic. The only thing a static type checker can go on is the type information provided in the `__call__` signature.
> 
> It looks like your metaclass is calling through to the standard `new.__call__` to perform most of its work. Could you provide more information about why you are overriding `__call__` in this manner? Is this just for an internal test class, or is this used in production code?
> 
> Currently the logic always skips `__new__` and `__init__` validation if there is a custom metaclass `__call__`. Perhaps the right answer here is to modify this to validate `__new__` and `__init__` if the metaclass `__call__` returns an instance of the `cls` type, which is the normal expected behavior for `__call__`. This would still make assumptions about the internal implementation about the `__call__` method that might be incorrect. For example, what if the `__call__` method does not call `__init__` on the class?
> 
> Another option is to leave the logic the way it is currently, and if you override `__call__` in your metaclass but want a static type checker to use the normal `new.__call__` logic, you could conditionalize the override with an `if not TYPE_CHECKING:` conditional.

Thank you for your explanation. It seems that the best choice for me is to use `overloads` now.

I can explain why I want to do such a thing:

```python
class TestMeta(type):
    def __call__(cls, *args, **kwargs):
        if not getattr(cls, "initialized", False):
            raise NotImplementedError(
                "super().__init__(...) should be used when deriving the subclass "
                "{0}".format(cls)
            )


class TestAbstract(metaclass=TestMeta):
    def __init__(self) -> None:
        # Do some internal stuff here.
        self.initialized = True


class TestDerived(TestAbstract):
    def __init__(self):
        return


# Now we do not allow to initialize TestDerived() in run-time program, because its
# implementation does not contain super().__init__()
TestDerived()
```

In this example, I assume that `TestAbstract` is designed by myself. It contains a lot of internal and required logic during the initialization. I expect that this class will be used and derived by the users. However, I cannot guarantee that `super().__init__()` is used by the users, so I use this `TestMeta` to perform a check during the instantiation.

**Comment by erictraut** [comment]
OK, then I'm going to leave the current logic as is.

**Comment by cainmagi** [comment]
Hello, Eric! @erictraut 

I have thought about this issue again. Actually it is potentially related to another issue about `ParamSpec`, for example:

```python
from typing import Callable
from typing_extensions import ParamSpec, TypeVar, reveal_type


P = ParamSpec("P")
S = TypeVar("S")
T = TypeVar("T")


def func1(val1: T, val2: S, val3: S) -> T:
    ...


def func2(func: Callable[P, T], *args: P.args, **kwargs: P.kwargs) -> T:
    ...


# val2 should has the same type of val3, but here raise no issues.
# val1 is incorrectly annotated as `T@func1`
# val2 is incorrectly annotated as `S@func1`
# val3 is annotated as int
# Type check does not know that val2 and val3 have the same type.
reveal_type(func2(func1, val1=1, val2=3, val3="s"))  # Annotated as `T@func1` which is expected to be `int` here.
```
I suspect that `ParamSpec` does not successfully forward every argument to the generic type used in `func1`, thus causing this problem. Should this issue get fixed? If it can work as I expected, I think my solution based on using `Protocol` to annotate metaclass `__call__` will work. 

Thank you!

**Comment by erictraut** [comment]
This appears to have nothing to do with the original issue. Please open a new issue if you would like to report a different bug.

**Comment by cainmagi** [comment]
> This appears to have nothing to do with the original issue. Please open a new issue if you would like to report a different bug.

Thank you. I have submitted it to #5495, where I have provided further experiments.

**Comment by erictraut** [comment]
I've decided to revisit the design based on input from multiple pyright users. I've adjusted the heuristics so a metaclass `__call__` override that returns an `Any` will prefer the return type of the class `__new__` method rather than `Any`. This will be included in the next release.

**Comment by cainmagi** [comment]
Thank you! If this feature can be provided, it will help me a lot!

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.320, which I just published. It will also be included in a future version of pylance.

**Comment by cainmagi** [comment]
Hello, @erictraut!

I am not sure whether the following usages are legal or not. It seems that the high-order issue of `ParamSpec` still exists in the following usages:

```python
from typing import Generic, TypeVar, Callable, Type
from typing_extensions import ParamSpec, Protocol, reveal_type


P = ParamSpec("P")
T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)


class TestProtocol(Protocol[P, T_co]):
    def __init__(self, *args: P.args, **kwargs: P.kwargs) -> None:
        ...

    def __new__(cls) -> T_co:
        ...


class Test(Generic[T]):
    def __init__(self, val1: T, val2: int) -> None:
        ...


def test2(val1: T, val2: int) -> Test[T]:
    ...


def func(obj: Callable[P, T], *args: P.args, **kwargs: P.kwargs) -> T:
    ...


def func2(obj: Type[TestProtocol[P, T]], *args: P.args, **kwargs: P.kwargs) -> T:
    ...


val_test = Test(val1=1, val2=2)


reveal_type(Test(val1=1, val2=2))  # Test[int], as expected.
reveal_type(test2(val1=1, val2=2))  # Test[int], as expected.
reveal_type(func(Test, val1=1, val2=2))  # Test[Unknown], however, expecting Test[int].
reveal_type(func2(Test, val1=1, val2=2))  # Test[Unknown], however, expecting Test[int].
```

This issue prevents me from defining a function accepting a "generic" instance constructor as its argument. 

By the way, I think the definition of `func2` may be problematic because it assumes the returned value of `TestProtocol.__new__` to be the returned value of the constructor. However, the type checker does not raise warnings here.

Pylance: 2023.8.10
Pyright: 932e542d

Thank you!
