### ISSUE TITLE
relative imports not handled

### ISSUE THREAD

**Issue by klix2** [Microsoft/pyright#58]
relative imports within a package get flagged as import could not be resolved
from .test1 import a

to reproduce 
you need:
a package directory containing 2 python files:
test2.py
```
a=1
```
test1.py
````
from .test2 import a
````
-> gets flagged as import could not be resolved by pyright

pyright 1.08 as extension of vscode

python 3.7 from anaconda distribution on windows 10
i have added the files to reproduce the issue

[test.zip](https://github.com/Microsoft/pyright/files/3049562/test.zip)

**Comment by erictraut** [comment]
I think I've found and addressed this problem. The fix will be in the next published version (1.0.9).

**Comment by erictraut** [comment]
This is fixed in 1.0.9, which I just published. Thanks again for the bug report.

**Comment by lexs** [comment]
I am still seeing this with 1.0.24. I've never seen it work but let me know if you need a repro.
