### ISSUE TITLE
variable wrongly inferenced to be of type Never

### ISSUE THREAD

**Issue by lumpi101** [microsoft/pyright#724]
**Describe the bug**
The first code snippet below (reduced to a minimal "working" example) produces a "reportGeneralTypeIssues" error from pyright in the last line (`x += 44`). The popup-message says: 'Operator "+" not supported for types "Never" and "Literal[44]"Pyright (reportGeneralTypeIssues)'

Type-hinting the variable "x" to be int `x: int = 0` at the beginning fixes the problem in that case. But it's possible to slightly modify the example that even then the error occurs - shown in the second code snippet.

**To Reproduce**
Open VS Code with pyright, create a plain .py file and insert one of the code snippets below.

**Expected behavior**
Pyright doesn't show any issues.

**Screenshots or Code**
first code snippet:
```python
a = False
x = 0

while len(input()) < 42:
    x += 43
    if a:
        print('foo')
    x += 44
```

second code snippet:
```python
a: bool = False
x: int = 0

while len(input()) < 42:
    x += 43
    if a and a:
        print('foo')
        continue
    x += 44
```

**VS Code extension or command-line**
I'm running pyright as a VS Code extension.
Pyright version: v1.1.41
VS Code version: Version: 1.46.0 (system setup)
OS: Windows_NT x64 10.0.18363

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next published version of Pyright.

**Comment by erictraut** [comment]
This is now addressed in Pyright 1.1.42, which was just published.

**Comment by lumpi101** [comment]
Perfect, thx for the quick fix!

**Comment by lumpi101** [comment]
I just saw that in my actual project there is still an issue. So I again reduced it to a minimal example:

```python
a: bool = False
x: int = 0

while len(input()) < 42:
    
    x += 43

    if a and a:
        print('foo')
        continue

    if a:
        print('bar')
        continue
    
    x += 44
```

It's again the last line which produces the same Issue as before.

Now, I am using Pyright v1.1.42

**Comment by erictraut** [comment]
Thanks for the bug report. This is now fixed in 1.1.43, which I just published.
