### ISSUE TITLE
Error unpacking tuple when calling a vararg function

### ISSUE THREAD

**Issue by russelldavis** [microsoft/pyright#845]
```python
def foo1(a, b):
    print(a, b)

def foo2(*args):
    print(*args)

bar = (2,3)
foo1(*bar) # No problem
foo2(*bar) # Pyright error: "Expected 1 positional argument"
```

See the error on the final line. The code is valid and runs fine.

**Comment by erictraut** [comment]
Thanks for the bug report. Great example.

This will be fixed in the next version of Pyright / Pylance.

**Comment by erictraut** [comment]
This is now fixed in Pyright 1.1.54, which I just published. It will also be included in the next release of Pylance.

**Comment by muhammedfurkan** [comment]
> ```python
> def foo1(a, b):
>     print(a, b)
> 
> def foo2(*args):
>     print(*args)
> 
> bar = (2,3)
> foo1(*bar) # No problem
> foo2(*bar) # Pyright error: "Expected 1 positional argument"
> ```
> 
> See the error on the final line. The code is valid and runs fine.

I still have this problem in _Pylance v2020.12.1-pre.1_ version

**Comment by erictraut** [comment]
This issue was fixed in July, and code was added to the pyright test suite to cover this case. I'm not able to repro this in either pyright or pylance. Are you able to repro it with the exact code that you've pasted above? If so, then I suspect you're not running the version of pylance that you think you are. If it's a different piece of code that's resulting in the problem, please paste that here so we can investigate further.
