### ISSUE TITLE
Support for cython

### ISSUE THREAD

**Issue by tobiasdiez** [microsoft/pyright#952]
**Is your feature request related to a problem? Please describe.**
Cython files (or the `--inplace` compiled versions) are currently not recognized, and pyright warns that the imports could not be resolved if a `cpx` file is imported in a normal python file.

**Describe the solution you'd like**
Recognize cpx and/or compiled `so` / `pyd` files.

**Comment by erictraut** [comment]
I'm not familiar with the naming convention used for cpx files. Is it simply <module>.cpx? Is it the same on all platforms, or does it include a platform-specific component?

**Comment by erictraut** [comment]
@jakebailey do you see any downside to including ".cpx" in the list of recognized binary files alongside ".so" and ".pyd"?

**Comment by jakebailey** [comment]
I'm not familiar with the extension, I thought cython source files had the extension `pyx`.

These source formats are different than the binary counterparts which may or may not include platform/interpreter version info, but I can't say generically that their naming convention is always 1:1 with the module name / location, though my impression is yes.

**Comment by tobiasdiez** [comment]
Sorry, my fault, the file extension for the uncompiled cython file is indeed `pyx` (or `pxd` and `pxi`). The compiled file usually contains an additional "compilation string", e.g. `closure.cpython-37m-x86_64-linux-gnu.so` for the file `closure.pxd`.

Thanks for having a look at this.

**Comment by erictraut** [comment]
If I understand correctly, a ".pyx" file contains uncompiled cython source. This file contains text, but it is not true Python and can't be interpreted as such by a Python interpreter or type checker. But once this is compiled by cython, a native binary (like ".so") is produced. So if you install a package created with cython, the ".so" or ".pyd" file will be present after the install. Is that correct?

Pyright already supports ".so" and ".pyd" files, so what additional support is needed here?

**Comment by tobiasdiez** [comment]
Given the following files (in the same folder).
- `a.py` containing `import b`
- `b.pyx` containing some Cython code

Then the import statement in file `a` is marked as unresolved. Even if the Cython code is compiled using `--inplace`, leading to a `b.cypthon-xyz.so` file in the same folder, the import is still not resolved.

**Comment by erictraut** [comment]
Pyright already contains code to handle binary files with names of the form "<module>.<cpython-xyz>.so". It does so by extracting the module name (the characters up to the first dot) and comparing that against the import name. I've tested this, and it seems to work fine.

Could you please do an in-place compile and verify that an ".so" file is created in the same directory. Once the ".so" file is present, pyright should use it to resolve the import. If it doesn't immediately recognize the import, try restarting the pyright language service (command-shift-P, then type "Restart Server") and see if it then successfully resolves the import.

If that still doesn't work, please post the name of the import plus the full file name of the ".so" file. Thanks.

**Comment by erictraut** [comment]
@tobiasdiez, just checking back with you to make sure you saw my question above.

**Comment by erictraut** [comment]
@tobiasdiez, I'm going to close this since I haven't heard back from you. If you have additional information, please feel free to add to this issue, and I'll take another look.

**Comment by tobiasdiez** [comment]
Sorry for the late answer, I was away for a few days.

In the code (placed in /src/sage/manifolds/differentiable/manifold.py):
```
from sage.rings.integer import Integer
from sage.rings.infinity import infinity, minus_infinity
```
The first import is not correctly resolved, while the second is.
In /src/sage/rings, the following files are present (among others):
```
infinity.py
integer.c
integer.cpython-37m-x86_64-linux-gnu.so
integer.pxd
integer.pyx
```
Thus, the python file is correctly found, but not the compiled cython file.
The error persists even after restarting the language server.

**Comment by erictraut** [comment]
OK, thanks for the additional details. I was able to repro the problem. The import resolution logic was properly handling binaries (e.g. ".so" files), but it was allowing them only for site-packages, not for local (workspace) packages. I've changed the logic to allow for binaries in both places. This fix will be in the next release of Pyright.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.67, which I just published. It will also be included in next week's release of Pylance.

**Comment by tobiasdiez** [comment]
Thanks @erictraut for working on this, and sorry for the late response.

Sadly, the issues is not yet fixed in the latest released version of pylance in VS code (v2020.11.2) for me. The setup is the same as in https://github.com/microsoft/pyright/issues/952#issuecomment-687177237, and hovering over `from sage.rings.integer import Integer` only reveals `(import) Integer: Any`.

**Comment by erictraut** [comment]
Are you still receiving an import resolution error? The bug fix was to fix that issue. 

Type information is available only for Python code, so symbols imported from native code will always have an "Any" (or "Unknown") type. So it sounds like it's working as expected.

**Comment by tobiasdiez** [comment]
Ah ok, then it is working as expected. There is indeed no longer an error that the import cannot be resolved. Thanks!

Are there any plans to support type annotation for native code?

**Comment by erictraut** [comment]
Native code libraries are shipped as binaries, so they have no type detailed information beyond top-level symbols. The right approach is to encourage package maintainers to include stub files that provide detailed type information. There has been some talk about providing additional tooling to help in the creation and maintenance of these stubs, but that would be an effort outside of pyright and other type checkers.

**Comment by tobiasdiez** [comment]
@erictraut What's the status of these additional tools for creating stubs (from cython code). I couldn't find anything, but hopefully I've overlooked something.

**Comment by erictraut** [comment]
No status to report. It's unlikely that we will be investing in this. If you would like to build a tool that converts cython code into type stubs that can be used by pyright and other Python type tools, the community would benefit from such a tool.
